services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./src/Dockerfile.dev
    working_dir: /home/node/app
    env_file:
      - ./src/.env
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'