services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./src/Dockerfile.prod
    working_dir: /home/node/app
    env_file:
      - ./src/.env.local
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`rutafem.com`)"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.tls.certresolver=myresolver"
    networks:
      - traefik_routing

networks:
  traefik_routing:
    external: true